// KoPlatformInput.cpp — SDL tarama kodları ↔ DirectInput (DIK_*) / sanal tuş (VK_*) eşlemesi.
#include "KoPlatformInput.h"

#include <windows.h>
#include <dinput.h>

#include <SDL.h>

#include <cstring>

namespace
{
struct DikMap
{
	int dik;
	SDL_Scancode sc;
};

const DikMap kDikMap[] = {
	{DIK_ESCAPE, SDL_SCANCODE_ESCAPE}, {DIK_1, SDL_SCANCODE_1}, {DIK_2, SDL_SCANCODE_2}, {DIK_3, SDL_SCANCODE_3},
	{DIK_4, SDL_SCANCODE_4}, {DIK_5, SDL_SCANCODE_5}, {DIK_6, SDL_SCANCODE_6}, {DIK_7, SDL_SCANCODE_7},
	{DIK_8, SDL_SCANCODE_8}, {DIK_9, SDL_SCANCODE_9}, {DIK_0, SDL_SCANCODE_0}, {DIK_MINUS, SDL_SCANCODE_MINUS},
	{DIK_EQUALS, SDL_SCANCODE_EQUALS}, {DIK_BACK, SDL_SCANCODE_BACKSPACE}, {DIK_TAB, SDL_SCANCODE_TAB},
	{DIK_Q, SDL_SCANCODE_Q}, {DIK_W, SDL_SCANCODE_W}, {DIK_E, SDL_SCANCODE_E}, {DIK_R, SDL_SCANCODE_R},
	{DIK_T, SDL_SCANCODE_T}, {DIK_Y, SDL_SCANCODE_Y}, {DIK_U, SDL_SCANCODE_U}, {DIK_I, SDL_SCANCODE_I},
	{DIK_O, SDL_SCANCODE_O}, {DIK_P, SDL_SCANCODE_P}, {DIK_LBRACKET, SDL_SCANCODE_LEFTBRACKET},
	{DIK_RBRACKET, SDL_SCANCODE_RIGHTBRACKET}, {DIK_RETURN, SDL_SCANCODE_RETURN}, {DIK_LCONTROL, SDL_SCANCODE_LCTRL},
	{DIK_A, SDL_SCANCODE_A}, {DIK_S, SDL_SCANCODE_S}, {DIK_D, SDL_SCANCODE_D}, {DIK_F, SDL_SCANCODE_F},
	{DIK_G, SDL_SCANCODE_G}, {DIK_H, SDL_SCANCODE_H}, {DIK_J, SDL_SCANCODE_J}, {DIK_K, SDL_SCANCODE_K},
	{DIK_L, SDL_SCANCODE_L}, {DIK_SEMICOLON, SDL_SCANCODE_SEMICOLON}, {DIK_APOSTROPHE, SDL_SCANCODE_APOSTROPHE},
	{DIK_GRAVE, SDL_SCANCODE_GRAVE}, {DIK_LSHIFT, SDL_SCANCODE_LSHIFT}, {DIK_BACKSLASH, SDL_SCANCODE_BACKSLASH},
	{DIK_Z, SDL_SCANCODE_Z}, {DIK_X, SDL_SCANCODE_X}, {DIK_C, SDL_SCANCODE_C}, {DIK_V, SDL_SCANCODE_V},
	{DIK_B, SDL_SCANCODE_B}, {DIK_N, SDL_SCANCODE_N}, {DIK_M, SDL_SCANCODE_M}, {DIK_COMMA, SDL_SCANCODE_COMMA},
	{DIK_PERIOD, SDL_SCANCODE_PERIOD}, {DIK_SLASH, SDL_SCANCODE_SLASH}, {DIK_RSHIFT, SDL_SCANCODE_RSHIFT},
	{DIK_MULTIPLY, SDL_SCANCODE_KP_MULTIPLY}, {DIK_LMENU, SDL_SCANCODE_LALT}, {DIK_SPACE, SDL_SCANCODE_SPACE},
	{DIK_CAPITAL, SDL_SCANCODE_CAPSLOCK}, {DIK_F1, SDL_SCANCODE_F1}, {DIK_F2, SDL_SCANCODE_F2}, {DIK_F3, SDL_SCANCODE_F3},
	{DIK_F4, SDL_SCANCODE_F4}, {DIK_F5, SDL_SCANCODE_F5}, {DIK_F6, SDL_SCANCODE_F6}, {DIK_F7, SDL_SCANCODE_F7},
	{DIK_F8, SDL_SCANCODE_F8}, {DIK_F9, SDL_SCANCODE_F9}, {DIK_F10, SDL_SCANCODE_F10}, {DIK_NUMLOCK, SDL_SCANCODE_NUMLOCKCLEAR},
	{DIK_SCROLL, SDL_SCANCODE_SCROLLLOCK}, {DIK_NUMPAD7, SDL_SCANCODE_KP_7}, {DIK_NUMPAD8, SDL_SCANCODE_KP_8},
	{DIK_NUMPAD9, SDL_SCANCODE_KP_9}, {DIK_SUBTRACT, SDL_SCANCODE_KP_MINUS}, {DIK_NUMPAD4, SDL_SCANCODE_KP_4},
	{DIK_NUMPAD5, SDL_SCANCODE_KP_5}, {DIK_NUMPAD6, SDL_SCANCODE_KP_6}, {DIK_ADD, SDL_SCANCODE_KP_PLUS},
	{DIK_NUMPAD1, SDL_SCANCODE_KP_1}, {DIK_NUMPAD2, SDL_SCANCODE_KP_2}, {DIK_NUMPAD3, SDL_SCANCODE_KP_3},
	{DIK_NUMPAD0, SDL_SCANCODE_KP_0}, {DIK_DECIMAL, SDL_SCANCODE_KP_PERIOD}, {DIK_F11, SDL_SCANCODE_F11},
	{DIK_F12, SDL_SCANCODE_F12}, {DIK_NUMPADENTER, SDL_SCANCODE_KP_ENTER}, {DIK_RCONTROL, SDL_SCANCODE_RCTRL},
	{DIK_DIVIDE, SDL_SCANCODE_KP_DIVIDE}, {DIK_SYSRQ, SDL_SCANCODE_PRINTSCREEN}, {DIK_RMENU, SDL_SCANCODE_RALT},
	{DIK_PAUSE, SDL_SCANCODE_PAUSE}, {DIK_HOME, SDL_SCANCODE_HOME}, {DIK_UP, SDL_SCANCODE_UP}, {DIK_PRIOR, SDL_SCANCODE_PAGEUP},
	{DIK_LEFT, SDL_SCANCODE_LEFT}, {DIK_RIGHT, SDL_SCANCODE_RIGHT}, {DIK_END, SDL_SCANCODE_END}, {DIK_DOWN, SDL_SCANCODE_DOWN},
	{DIK_NEXT, SDL_SCANCODE_PAGEDOWN}, {DIK_INSERT, SDL_SCANCODE_INSERT}, {DIK_DELETE, SDL_SCANCODE_DELETE},
	{DIK_LWIN, SDL_SCANCODE_LGUI}, {DIK_RWIN, SDL_SCANCODE_RGUI}, {DIK_APPS, SDL_SCANCODE_APPLICATION},
};

SDL_Scancode VkToScancode(int vk)
{
	if (vk >= 'A' && vk <= 'Z')
		return (SDL_Scancode) (SDL_SCANCODE_A + (vk - 'A'));
	if (vk >= '0' && vk <= '9')
		return vk == '0' ? SDL_SCANCODE_0 : (SDL_Scancode) (SDL_SCANCODE_1 + (vk - '1'));
	if (vk >= VK_F1 && vk <= VK_F12)
		return (SDL_Scancode) (SDL_SCANCODE_F1 + (vk - VK_F1));
	switch (vk)
	{
		case VK_BACK: return SDL_SCANCODE_BACKSPACE;
		case VK_TAB: return SDL_SCANCODE_TAB;
		case VK_RETURN: return SDL_SCANCODE_RETURN;
		case VK_ESCAPE: return SDL_SCANCODE_ESCAPE;
		case VK_SPACE: return SDL_SCANCODE_SPACE;
		case VK_PRIOR: return SDL_SCANCODE_PAGEUP;
		case VK_NEXT: return SDL_SCANCODE_PAGEDOWN;
		case VK_END: return SDL_SCANCODE_END;
		case VK_HOME: return SDL_SCANCODE_HOME;
		case VK_LEFT: return SDL_SCANCODE_LEFT;
		case VK_UP: return SDL_SCANCODE_UP;
		case VK_RIGHT: return SDL_SCANCODE_RIGHT;
		case VK_DOWN: return SDL_SCANCODE_DOWN;
		case VK_INSERT: return SDL_SCANCODE_INSERT;
		case VK_DELETE: return SDL_SCANCODE_DELETE;
		case VK_SNAPSHOT: return SDL_SCANCODE_PRINTSCREEN;
		case VK_LSHIFT: return SDL_SCANCODE_LSHIFT;
		case VK_RSHIFT: return SDL_SCANCODE_RSHIFT;
		case VK_LCONTROL: return SDL_SCANCODE_LCTRL;
		case VK_RCONTROL: return SDL_SCANCODE_RCTRL;
		case VK_LMENU: return SDL_SCANCODE_LALT;
		case VK_RMENU: return SDL_SCANCODE_RALT;
		default: return SDL_SCANCODE_UNKNOWN;
	}
}
} // namespace

KoInputState& KoInput()
{
	static KoInputState s;
	return s;
}

void KoInputUpdateKeyboard()
{
	KoInputState& st  = KoInput();
	int n             = 0;
	const Uint8* keys = SDL_GetKeyboardState(&n);
	std::memset(st.keysDIK, 0, sizeof(st.keysDIK));
	if (!keys || !st.windowFocused)
		return;
	for (const DikMap& m : kDikMap)
		if (m.sc < n && keys[m.sc])
			st.keysDIK[m.dik] = 0x80;
}

int KoInputIsVkDown(int vk)
{
	const KoInputState& st = KoInput();
	switch (vk)
	{
		case VK_LBUTTON: return st.lbDown;
		case VK_MBUTTON: return st.mbDown;
		case VK_RBUTTON: return st.rbDown;
		case VK_SHIFT: return KoInputIsVkDown(VK_LSHIFT) || KoInputIsVkDown(VK_RSHIFT);
		case VK_CONTROL: return KoInputIsVkDown(VK_LCONTROL) || KoInputIsVkDown(VK_RCONTROL);
		case VK_MENU: return KoInputIsVkDown(VK_LMENU) || KoInputIsVkDown(VK_RMENU);
		default: break;
	}
	int n             = 0;
	const Uint8* keys = SDL_GetKeyboardState(&n);
	SDL_Scancode sc   = VkToScancode(vk);
	return (keys && sc != SDL_SCANCODE_UNKNOWN && sc < n && keys[sc]) ? 1 : 0;
}
